# NumPy Basics: Arrays and Vectorized Computation

- __NumPy, short for Numerical Python__
- __It is one of the most important foundational packages for numerical computing in Python__

In [2]:
# Example of numpy
#range == arange in numpy

import numpy as np
my_data = np.arange(10)
my_data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_list = list(np.arange(15))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

- __%time => It also provides functionality other than representing time, like waiting during code execution and measuring the efficiency of your code__

In [17]:
# Now let's multiply each sequence by 2

%time for _ in range(10): my_data2 = my_data * 2

CPU times: user 56 µs, sys: 11 µs, total: 67 µs
Wall time: 73.7 µs


- __NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory__

In [20]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 84 µs, sys: 16 µs, total: 100 µs
Wall time: 110 µs


### The NumPy ndarray: A Multidimensional Array Object

In [22]:
#Example of nd_array

import numpy as np

nd_array = np.random.rand(2,3)
nd_array

array([[0.88415547, 0.03340967, 0.57050258],
       [0.08909221, 0.29618377, 0.08553765]])

In [23]:
# we can do also mathmatical operation

op_nd_array = nd_array * 10
op_nd_array

array([[8.84155469, 0.33409674, 5.70502579],
       [0.89092211, 2.96183767, 0.8553765 ]])

In [25]:
op_nd_array.shape

(2, 3)

In [27]:
op_nd_array.dtype

dtype('float64')

### Creating Arrays
- __The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data__

In [33]:
# Example of creating array from list


import numpy as np

a_data = [10,20,30,40,50,60,70,80,90]
a_array = np.array(a_data)
a_array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Another example

b_data = [[1,2,3,4,5],[10,20,30,40,50]]
b_array = np.array(b_data)
b_array

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [36]:
# Another way of creating array

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.empty((3,4))

array([[2.4087139e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [43]:
#create array with datatype

c_array = np.arange((10), dtype =np.float64)
c_array
c_array.dtype

dtype('float64')

In [45]:
d_array = np.arange((10), dtype=np.int32)
d_array
d_array.dtype

dtype('int32')

- __Convert datatype__
- __'astype' function convert datatype__

In [46]:
e_array = np.array([10,20,30,40,50])
e_array

array([10, 20, 30, 40, 50])

In [47]:
f_array = e_array.astype(np.float64)
f_array

array([10., 20., 30., 40., 50.])

### Arithmetic with NumPy Arrays

In [50]:
# Some basic arithmatic examples

g_array = np.array([[1,2,3,4,5],[10,20,30,40,50]])
g_array*3

array([[  3,   6,   9,  12,  15],
       [ 30,  60,  90, 120, 150]])

In [51]:
h_array = g_array * g_array
h_array

array([[   1,    4,    9,   16,   25],
       [ 100,  400,  900, 1600, 2500]])

In [52]:
i_array = h_array**2
i_array

array([[      1,      16,      81,     256,     625],
       [  10000,  160000,  810000, 2560000, 6250000]])

In [53]:
j_array = h_array>g_array
j_array

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### Basic Indexing and Slicing

In [55]:
# example of indexing

k_array = np.array([1,2,3,4,5,6,7,8,9,10,11,1,2,13,14,15])

array([6, 7, 8])

In [56]:
k_array[5:8]

array([6, 7, 8])

In [59]:
k_array[5:8] = 0

k_array 

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10, 11,  1,  2, 13, 14, 15])

In [60]:
k_array[5:8]

array([0, 0, 0])

In [61]:
k_array[-1]

15

In [63]:
k_array[:-3]

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10, 11,  1,  2])

- __ndimension array indexing__

In [120]:
l_array = np.array([[1,2,3,4,5],[11,22,33,44,55],[10,20,30,40,50]])
l_array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [10, 20, 30, 40, 50]])

In [121]:
l_array[2]

array([10, 20, 30, 40, 50])

In [122]:
l_array[2][0]

10

In [123]:
l_array[2][-1]

50

In [124]:
l_array[2][0:-1]

array([10, 20, 30, 40])

In [125]:
m_array = np.array([[[1,2,3,4,5,],[10,20,30,40,50]],[[11,22,33,44,55],[100,200,300,400,500]]])
m_array

array([[[  1,   2,   3,   4,   5],
        [ 10,  20,  30,  40,  50]],

       [[ 11,  22,  33,  44,  55],
        [100, 200, 300, 400, 500]]])

In [126]:
m_array[0]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [127]:
m_array[0][1]

array([10, 20, 30, 40, 50])

In [128]:
m_array[0][1][-1]

50

- __We can assign both scaler and  array values to m_array[0]__

In [129]:
old_values = m_array[0].copy()
old_values

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [130]:
# Now let's assign value to m_array[0]

m_array[0] = 999
m_array[0]

array([[999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999]])

In [133]:
m_array[0] = old_values
m_array[0]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [134]:
m_array

array([[[  1,   2,   3,   4,   5],
        [ 10,  20,  30,  40,  50]],

       [[ 11,  22,  33,  44,  55],
        [100, 200, 300, 400, 500]]])

- __Indexing with slices__


In [138]:
n_array = np.array([[1,2,3,4,5],[11,22,33,44,55],[10,20,30,40,50]])

In [139]:
n_array[:2]

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [141]:
n_array[:2]

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [142]:
n_array[:2,:-3]

array([[ 1,  2],
       [11, 22]])

In [143]:
n_array[:2,2:]

array([[ 3,  4,  5],
       [33, 44, 55]])

In [145]:
n_array[:,:1]

array([[ 1],
       [11],
       [10]])

In [146]:
# assing value

n_array[:,:1] = 0
n_array

array([[ 0,  2,  3,  4,  5],
       [ 0, 22, 33, 44, 55],
       [ 0, 20, 30, 40, 50]])

### Boolean Indexing


In [147]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [151]:
data = np.random.randn(7, 4)
data

array([[-0.93732368,  0.84315287,  0.64762758, -1.51619222],
       [-0.17516496, -0.71131469,  0.93037684,  1.43853242],
       [-0.43118511,  0.03281752, -1.15804405, -0.75730202],
       [ 1.20071579,  1.20412027, -1.40552447, -0.43563302],
       [ 0.48752352, -0.52494274, -0.89599309, -0.19598958],
       [-0.74496032, -0.4592035 , -0.17099975,  1.00343061],
       [ 0.52032811, -0.33173973,  0.36954095, -0.04638408]])

In [152]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

- __Bob name is in 0 index and 3 index , so it will also select the data from that index__



In [154]:
data[names == 'Bob']

array([[-0.93732368,  0.84315287,  0.64762758, -1.51619222],
       [ 1.20071579,  1.20412027, -1.40552447, -0.43563302]])

In [156]:
data[names == 'Bob',2:]

array([[ 0.64762758, -1.51619222],
       [-1.40552447, -0.43563302]])

- __To select everything but 'Bob' , you can either use != or negate the condition using ~__


In [157]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [158]:
data[~(names == 'Bob')]

array([[-0.17516496, -0.71131469,  0.93037684,  1.43853242],
       [-0.43118511,  0.03281752, -1.15804405, -0.75730202],
       [ 0.48752352, -0.52494274, -0.89599309, -0.19598958],
       [-0.74496032, -0.4592035 , -0.17099975,  1.00343061],
       [ 0.52032811, -0.33173973,  0.36954095, -0.04638408]])

- __Selecting more than one name__

In [160]:
select_name = (names == 'Bob') | (names == 'Will')
select_name

array([ True, False,  True,  True,  True, False, False])

In [162]:
data[select_name]

array([[-0.93732368,  0.84315287,  0.64762758, -1.51619222],
       [-0.43118511,  0.03281752, -1.15804405, -0.75730202],
       [ 1.20071579,  1.20412027, -1.40552447, -0.43563302],
       [ 0.48752352, -0.52494274, -0.89599309, -0.19598958]])

In [163]:
data[select_name] = 7
data[select_name]

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [164]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.17516496, -0.71131469,  0.93037684,  1.43853242],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.74496032, -0.4592035 , -0.17099975,  1.00343061],
       [ 0.52032811, -0.33173973,  0.36954095, -0.04638408]])

##### Fancy Indexing
- __Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays__

In [165]:
arr = np.empty((8, 4))
arr

array([[2.27246956e-316, 0.00000000e+000, 6.92256433e-310,
        6.92256432e-310],
       [6.92256558e-310, 6.92256433e-310, 6.92256433e-310,
        6.92256554e-310],
       [6.92256433e-310, 6.92256547e-310, 6.92256548e-310,
        6.92256558e-310],
       [6.92256433e-310, 6.92256432e-310, 6.92256433e-310,
        6.92256433e-310],
       [6.92256433e-310, 6.92256548e-310, 6.92256544e-310,
        6.92256433e-310],
       [6.92256558e-310, 6.92256558e-310, 6.92256433e-310,
        6.92256433e-310],
       [6.92256551e-310, 6.92256433e-310, 6.92256433e-310,
        6.92256433e-310],
       [6.92256433e-310, 6.92256558e-310, 6.92256558e-310,
        6.92256558e-310]])

In [168]:
arr[[4,3]]

array([[6.92256433e-310, 6.92256548e-310, 6.92256544e-310,
        6.92256433e-310],
       [6.92256433e-310, 6.92256432e-310, 6.92256433e-310,
        6.92256433e-310]])

#### Transposing Arrays and Swapping Axes
- __Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything__
- __Arrays have the transpose method and also the special T attribute__



In [172]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [171]:
# T attribute

arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [175]:
# Anothe example:-

arr_2 = np.random.rand(7,3)
arr_2

array([[0.99263292, 0.84634052, 0.43279473],
       [0.69237694, 0.54211436, 0.5074233 ],
       [0.91240298, 0.18531899, 0.07949051],
       [0.35139278, 0.3709864 , 0.20503946],
       [0.21120884, 0.8748796 , 0.13988723],
       [0.10824964, 0.63140157, 0.72880287],
       [0.78122982, 0.61673763, 0.62527744]])

In [176]:
arr_2.T

array([[0.99263292, 0.69237694, 0.91240298, 0.35139278, 0.21120884,
        0.10824964, 0.78122982],
       [0.84634052, 0.54211436, 0.18531899, 0.3709864 , 0.8748796 ,
        0.63140157, 0.61673763],
       [0.43279473, 0.5074233 , 0.07949051, 0.20503946, 0.13988723,
        0.72880287, 0.62527744]])

- __When doing matrix computations, you may do this very often—for example, when computing the inner matrix product using np.dot__

In [178]:
np.dot(arr_2.T, arr_2)

array([[3.08730922, 2.24984562, 1.5224347 ],
       [2.24984562, 2.72660184, 1.700355  ],
       [1.5224347 , 1.700355  , 1.43484353]])

- __For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes (for extra mind bending)__

In [188]:
arr_3 = np.arange(16).reshape((2, 2, 4))
arr_3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [184]:
arr_3.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [195]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

- __Simple transporting with T is a speacial case of swapping axes, ndarrays has the method awapaxes, which take the pair of axis number and switches the indicated axes to rerrange the data__


In [196]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])